name: actsub
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pip=24.2
  - cudatoolkit=11.6.0
  - pytorch=2.4.0
  - pytorch-cuda=12.4
  - torchvision=0.19.0
  - numpy=1.26.4
  - faiss=1.9.0
  - scikit-learn=1.5.1
  - tqdm=4.66.5
  - wandb=0.16.6
  - matplotlib=3.9.1
  - yaml=0.2.5
  - pyyaml=6.0.2
  - gdown=5.2.0
  - pandas=2.2.2
  - imgaug=0.4.0
  - scipy=1.14.1
  - json5=0.9.25
  - diffdist=0.1
  - statsmodels=0.14.2
  - timm=1.0.15
  - foolbox=3.3.1
  - pip:
      - libmr==0.1.9